### ISSUE TITLE
Could you example to upload file/image on Meteor JS?

### ISSUE THREAD

**Issue by thearabbit** [mbrookes/formsy-mui-demo#10]
I would like to upload file (pdf) and image on `Meteor`.
Could you example for me.

**Comment by mbrookes** [comment]
Out of scope of this lib, sorry.

**Comment by mbrookes** [comment]
Just as an aside, this is something like the 7th issue you've posted on this repo asking 'help' questions. So I had a quick look at your history, and I notice you've been spamming a lot of other maintainers with 'non-issues'.

While many will sigh, and patiently try to help. let me be the first to say: PLEASE STOP!

This is not what github issues is for, and it is an abuse of the people who contribute their time and their code to open source.

If you have found a genuine bug, and can give concrete steps to reproduce it, post an issue.

Otherwise, please find a more suitable forum for your questions (IRC, gitter, Stack Overflow etc.), and save github issues for its intended purpose.

Future issues from you on this or other repos I maintain will be closed without comment.

**Comment by thearabbit** [comment]
Sorry, Thanks.
